### ISSUE TITLE
Error: Query inactivity timeout

### ISSUE THREAD

**Issue by mauvm** [kukua/concava-mysql-influxdb#5]
Seems related to https://github.com/felixge/node-mysql/issues/1223, however ConCaVa runs in a Node v4.2.1 container. May be fixed by #4.

**Comment by mauvm** [comment]
```
{ [Error: Error: Query inactivity timeout] statusCode: 400 }
Error: Error: Query inactivity timeout
    at setMetadata.js:7:11
    at /data/node_modules/concava-adapter-mysql/lib/adapter.js:94:19
    at /data/node_modules/concava-adapter-mysql/node_modules/async-waterfall/index.js:47:20
    at handler (/data/node_modules/concava-adapter-mysql/node_modules/map-async/index.js:30:36)
    at Query._callback (/data/node_modules/concava-adapter-mysql/lib/adapter.js:153:20)
    at Query.Sequence.end (/data/node_modules/concava-adapter-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at /data/node_modules/concava-adapter-mysql/node_modules/mysql/lib/protocol/Protocol.js:399:18
    at Array.forEach (native)
    at /data/node_modules/concava-adapter-mysql/node_modules/mysql/lib/protocol/Protocol.js:398:13
    at doNTCallback0 (node.js:417:9)
```
